/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API Information
         * @description Get basic API information and available sources.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 📋 List Available Sources
         * @description Get all available media sources.
         */
        get: operations["get_sources_sources__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source}/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 📋 Get Source Configuration
         * @description Get configuration preferences for a specific source.
         */
        get: operations["get_source_preferences_sources__source__preferences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source}/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 🔍 Get Popular Content
         * @description Get popular content.
         */
        get: operations["get_popular_sources__source__popular_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source}/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 🔍 Get Latest Updates
         * @description Get latest updates.
         */
        get: operations["get_latest_updates_sources__source__latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 🔍 Search Content
         * @description Search for content.
         */
        get: operations["search_content_sources__source__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source}/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 🎬 Get Video Streaming Links
         * @description Get video sources.
         */
        get: operations["get_video_sources_sources__source__videos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/trailer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 🎬 Extract Streamable Trailer URL
         * @description Extract streamable URL from AniList or TMDB trailer data.
         *
         *     Takes trailer information from AniList or TMDB responses, builds the full YouTube URL,
         *     and uses ytdlp_extractor to get the actual streamable URL.
         *
         *     Args:
         *         request: TrailerRequest containing either anilist_trailer or tmdb_trailer data
         *
         *     Returns:
         *         TrailerResponse with streamable URL and metadata
         */
        get: operations["extract_trailer_url_sources_trailer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get overall series data (overview, no full episode list)
         * @description Get series overview data without full episode list.
         *
         *     This endpoint fetches basic series information including season/episode
         *     counts but not the full episode details. Use /series/seasons for
         *     full episode data.
         */
        get: operations["get_series_overview_sources__source__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source}/series/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all seasons with full episode data
         * @description Get all seasons for a series with full episode details.
         *
         *     This endpoint fetches the complete episode list organized by season,
         *     with TMDB data embedded in each season and episode.
         */
        get: operations["get_series_seasons_sources__source__series_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source}/series/seasons/{season_num}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get specific season with TMDB season details
         * @description Get details for a specific season with targeted TMDB lookup.
         *
         *     This endpoint fetches season-specific TMDB data including all episodes
         *     for that season only, with embedded tmdb_episode_data for each episode.
         */
        get: operations["get_series_season_sources__source__series_seasons__season_num__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source}/series/seasons/{season_num}/episodes/{episode_num}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get specific episode with TMDB episode details
         * @description Get details for a specific episode with targeted TMDB lookup.
         *
         *     This endpoint fetches episode-specific TMDB data including videos,
         *     images, crew, and guest stars for that episode only.
         */
        get: operations["get_series_episode_sources__source__series_seasons__season_num__episodes__episode_num__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source}/series/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all movies/OVAs for a series
         * @description Get all movies, OVAs, and specials for a series.
         */
        get: operations["get_series_movies_sources__source__series_movies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source}/series/movies/{movie_num}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get specific movie/OVA
         * @description Get details for a specific movie, OVA, or special.
         */
        get: operations["get_series_movie_sources__source__series_movies__movie_num__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/sources/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sources Status
         * @description Get status of all sources.
         */
        get: operations["get_sources_status_admin_sources_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/cache/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cache Stats
         * @description Get cache statistics.
         */
        get: operations["get_cache_stats_admin_cache_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/cache/clear/{prefix}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Cache Prefix
         * @description Clear cache entries with specific prefix.
         *
         *     Args:
         *         prefix: Cache key prefix to clear (e.g., 'anilist_search', 'tmdb_details', 'endpoints:aniworld:*')
         */
        post: operations["clear_cache_prefix_admin_cache_clear__prefix__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/cache/clear/endpoint/{endpoint_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Cache Endpoint
         * @description Clear cache entries for a specific endpoint.
         *
         *     Args:
         *         endpoint_path: Endpoint path to clear (e.g., 'aniworld/popular', 'anilist/search')
         */
        post: operations["clear_cache_endpoint_admin_cache_clear_endpoint__endpoint_path__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/cache/flush": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flush Cache
         * @description Flush all cache entries.
         */
        post: operations["flush_cache_admin_cache_flush_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ContentType
         * @description Content type enumeration for media sources.
         * @enum {string}
         */
        ContentType: "anime" | "series_movie" | "adult" | "unknown";
        /**
         * EnrichedEpisode
         * @description Episode with embedded TMDB episode data.
         *
         *     This model extends the base Episode with full TMDB episode details
         *     including crew, guest_stars, videos, and images.
         */
        EnrichedEpisode: {
            /**
             * Season
             * @description Season number for series episodes
             */
            season?: number | null;
            /**
             * Episode
             * @description Episode number within season
             */
            episode?: number | null;
            /**
             * Kind
             * @description Content kind: 'series', 'movie', 'ova', 'special'
             */
            kind?: string | null;
            /**
             * Number
             * @description Film number for movie collections
             */
            number?: number | null;
            /**
             * Title
             * @description Episode title from provider
             */
            title: string;
            /**
             * Name
             * @description Alternative episode name
             */
            name?: string | null;
            /**
             * Url
             * @description Streaming URL path
             */
            url: string;
            /**
             * Tags
             * @description Provider-specific tags
             */
            tags?: string[];
            /** @description Complete TMDB episode details including crew, guest_stars, videos, images */
            tmdb_episode_data?: components["schemas"]["TMDBEpisodeDetail"] | null;
        };
        /**
         * EnrichedSeason
         * @description Season with embedded TMDB season data.
         *
         *     This model extends the base Season with full TMDB season details
         *     and uses EnrichedEpisode for episodes.
         */
        EnrichedSeason: {
            /**
             * Season
             * @description Season number (0 for specials)
             */
            season: number;
            /**
             * Title
             * @description Season title from provider
             */
            title?: string | null;
            /**
             * Episodes
             * @description List of episodes with optional TMDB enrichment
             */
            episodes?: components["schemas"]["EnrichedEpisode"][];
            /** @description Complete TMDB season details including metadata, poster, videos, images */
            tmdb_season_data?: components["schemas"]["TMDBSeasonDetail"] | null;
            /**
             * Episode Count
             * @description Total episode count from TMDB (may differ from episodes list length)
             */
            episode_count?: number | null;
        };
        /**
         * Episode
         * @description Episode information (base model without TMDB enrichment).
         */
        Episode: {
            /** Season */
            season?: number | null;
            /** Episode */
            episode?: number | null;
            /** Kind */
            kind?: string | null;
            /** Number */
            number?: number | null;
            /** Title */
            title: string;
            /** Name */
            name?: string | null;
            /** Url */
            url: string;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * EpisodeResponse
         * @description Response for single episode with embedded TMDB data.
         */
        EpisodeResponse: {
            /** @description Type of content (anime, series_movie, adult) */
            content_type: components["schemas"]["ContentType"];
            /** @description Episode details with embedded TMDB episode data */
            episode: components["schemas"]["EnrichedEpisode"];
            /** @description Complete TMDB TV series details for context */
            tmdb_series_data?: components["schemas"]["TMDBTVDetail"] | null;
            /**
             * Match Confidence
             * @description Confidence score of TMDB match (0-1)
             */
            match_confidence?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MediaInfo
         * @description Detailed Media information.
         */
        MediaInfo: {
            /** Name */
            name: string;
            /** Cover Image Url */
            cover_image_url: string;
            /** Description */
            description: string;
            /** Genres */
            genres?: string[];
            /** Episodes */
            episodes?: components["schemas"]["Episode"][];
            /**
             * Seasons Length
             * @description Number of seasons
             */
            seasons_length?: number | null;
            /**
             * Alternative Titles
             * @description Alternative titles in different languages
             */
            alternative_titles?: string[];
            /**
             * Start Year
             * @description Start year of the series
             */
            start_year?: number | null;
            /**
             * End Year
             * @description End year of the series
             */
            end_year?: number | null;
            /**
             * Fsk Rating
             * @description FSK age rating (German rating system)
             */
            fsk_rating?: number | null;
            /**
             * Imdb Id
             * @description IMDB ID (e.g., 'tt36469298')
             */
            imdb_id?: string | null;
            /**
             * Country Of Origin
             * @description Country of origin
             */
            country_of_origin?: string | null;
            /**
             * Main Genre
             * @description Primary genre classification
             */
            main_genre?: string | null;
            /**
             * Directors
             * @description List of directors
             */
            directors?: string[];
            /**
             * Actors
             * @description List of main actors
             */
            actors?: string[];
            /**
             * Producers
             * @description List of production companies
             */
            producers?: string[];
            /**
             * Backdrop Url
             * @description Backdrop/banner image URL
             */
            backdrop_url?: string | null;
            /**
             * Series Id
             * @description Internal series ID from the provider
             */
            series_id?: string | null;
            /**
             * Trailer Url
             * @description Trailer or official website URL
             */
            trailer_url?: string | null;
            /**
             * Rating Value
             * @description User rating value (e.g., 3.0)
             */
            rating_value?: number | null;
            /**
             * Rating Count
             * @description Number of user ratings
             */
            rating_count?: number | null;
            /**
             * Available Languages
             * @description Available languages/audio tracks (de, en, de_sub, en_sub)
             */
            available_languages?: string[];
        };
        /**
         * Movie
         * @description Movie/OVA/Special information.
         */
        Movie: {
            /** Number */
            number: number;
            /** Title */
            title: string;
            kind: components["schemas"]["MovieKind"];
            /** Url */
            url: string;
            /** Date Upload */
            date_upload?: string | null;
            /** Tags */
            tags?: string[];
        };
        /**
         * MovieKind
         * @description Movie kind enumeration.
         * @enum {string}
         */
        MovieKind: "movie" | "ova" | "special";
        /**
         * MovieResponse
         * @description Response for single movie.
         */
        MovieResponse: {
            /** @description Type of content (anime, series_movie, adult) */
            content_type: components["schemas"]["ContentType"];
            /** @description Movie details */
            movie: components["schemas"]["Movie"];
            /** @description Complete TMDB movie details */
            tmdb_series_data?: components["schemas"]["TMDBMovieDetail"] | null;
            /**
             * Match Confidence
             * @description Confidence score of TMDB match (0-1)
             */
            match_confidence?: number | null;
        };
        /**
         * MoviesResponse
         * @description Response for movies list.
         */
        MoviesResponse: {
            /** @description Type of content (anime, series_movie, adult) */
            content_type: components["schemas"]["ContentType"];
            /**
             * Movies
             * @description List of movies, OVAs, and specials
             */
            movies: components["schemas"]["Movie"][];
            /**
             * Tmdb Series Data
             * @description Complete TMDB series or movie details
             */
            tmdb_series_data?: components["schemas"]["TMDBTVDetail"] | components["schemas"]["TMDBMovieDetail"] | null;
            /**
             * Match Confidence
             * @description Confidence score of TMDB match (0-1)
             */
            match_confidence?: number | null;
        };
        /**
         * PaginatedSearchResultResponse
         * @description Paginated response for search results with comprehensive metadata.
         * @example {
         *       "content_type": "anime",
         *       "items": [
         *         {
         *           "available_languages": [
         *             "de",
         *             "de_sub"
         *           ],
         *           "image_url": "https://example.com/image.jpg",
         *           "link": "/anime/stream/attack-on-titan",
         *           "name": "Attack on Titan",
         *           "provider": "AniWorld"
         *         }
         *       ],
         *       "pagination": {
         *         "has_next": true,
         *         "has_previous": false,
         *         "page": 1,
         *         "per_page": 15,
         *         "total_items": 100,
         *         "total_pages": 7
         *       }
         *     }
         */
        PaginatedSearchResultResponse: {
            /** @description Type of content (anime, series_movie, adult) */
            content_type: components["schemas"]["ContentType"];
            /**
             * Items
             * @description Search result items for current page
             */
            items: components["schemas"]["SearchResult"][];
            /** @description Pagination metadata */
            pagination: components["schemas"]["PaginationMetadata"];
        };
        /**
         * PaginationMetadata
         * @description Pagination metadata for list responses.
         */
        PaginationMetadata: {
            /**
             * Page
             * @description Current page number (1-based)
             */
            page: number;
            /**
             * Per Page
             * @description Items per page
             */
            per_page: number;
            /**
             * Total Items
             * @description Total number of items across all pages
             */
            total_items?: number | null;
            /**
             * Total Pages
             * @description Total number of pages
             */
            total_pages?: number | null;
            /**
             * Has Next
             * @description Whether there is a next page
             */
            has_next: boolean;
            /**
             * Has Previous
             * @description Whether there is a previous page
             */
            has_previous: boolean;
        };
        /**
         * PreferencesResponse
         * @description Response for source preferences/configuration.
         */
        PreferencesResponse: {
            /**
             * Preferences
             * @description Source configuration preferences
             */
            preferences: {
                [key: string]: unknown;
            };
        };
        /**
         * SearchResult
         * @description Search result item.
         */
        SearchResult: {
            /** Name */
            name: string;
            /** Image Url */
            image_url: string;
            /** Link */
            link: string;
            /** Provider */
            provider: string;
            /**
             * Available Languages
             * @description Available languages (de, en, sub, jp)
             */
            available_languages?: string[];
            media_info?: components["schemas"]["MediaInfo"] | null;
        };
        /**
         * Season
         * @description Season information.
         */
        Season: {
            /** Season */
            season: number;
            /** Title */
            title?: string | null;
            /** Episodes */
            episodes?: components["schemas"]["Episode"][];
        };
        /**
         * SeasonResponse
         * @description Response for single season with embedded TMDB data.
         */
        SeasonResponse: {
            /** @description Type of content (anime, series_movie, adult) */
            content_type: components["schemas"]["ContentType"];
            /** @description Season detail with episodes and embedded TMDB season data */
            season: components["schemas"]["EnrichedSeason"];
            /** @description Complete TMDB TV series details for context */
            tmdb_series_data?: components["schemas"]["TMDBTVDetail"] | null;
            /**
             * Match Confidence
             * @description Confidence score of TMDB match (0-1)
             */
            match_confidence?: number | null;
        };
        /**
         * SeasonsResponse
         * @description Response for seasons list with embedded TMDB data.
         */
        SeasonsResponse: {
            /** @description Type of content (anime, series_movie, adult) */
            content_type: components["schemas"]["ContentType"];
            /**
             * Seasons
             * @description List of all seasons with embedded TMDB data per season
             */
            seasons: components["schemas"]["EnrichedSeason"][];
            /** @description Complete TMDB TV series details */
            tmdb_series_data?: components["schemas"]["TMDBTVDetail"] | null;
            /**
             * Match Confidence
             * @description Confidence score of TMDB match (0-1)
             */
            match_confidence?: number | null;
        };
        /**
         * SeriesDetail
         * @description Hierarchical series detail with seasons and movies.
         */
        SeriesDetail: {
            /** Slug */
            slug: string;
            /** Seasons */
            seasons?: components["schemas"]["Season"][];
            /** Movies */
            movies?: components["schemas"]["Movie"][];
        };
        /**
         * SeriesDetailResponse
         * @description Response for hierarchical series detail with TMDB enrichment.
         */
        SeriesDetailResponse: {
            /** @description Type of content (anime, series_movie, adult) */
            content_type: components["schemas"]["ContentType"];
            /** @description Series detail with seasons and movies */
            series: components["schemas"]["SeriesDetail"];
            /**
             * Season Count
             * @description Total number of seasons
             */
            season_count?: number | null;
            /** @description Complete TMDB TV series details */
            tmdb_series_data?: components["schemas"]["TMDBTVDetail"] | null;
            /**
             * Match Confidence
             * @description Confidence score of TMDB match (0-1)
             */
            match_confidence?: number | null;
        };
        /**
         * SourcesResponse
         * @description Response for available sources list.
         */
        SourcesResponse: {
            /**
             * Sources
             * @description List of available source names
             */
            sources: string[];
        };
        /**
         * TMDBCreatedBy
         * @description TMDB created by person.
         */
        TMDBCreatedBy: {
            /** Id */
            id: number;
            /** Credit Id */
            credit_id: string;
            /** Name */
            name: string;
            /** Gender */
            gender: number;
            /** Profile Path */
            profile_path?: string | null;
        };
        /**
         * TMDBCrew
         * @description TMDB crew member model.
         */
        TMDBCrew: {
            /** Id */
            id: number;
            /** Credit Id */
            credit_id: string;
            /** Name */
            name: string;
            /** Department */
            department: string;
            /** Job */
            job: string;
            /** Profile Path */
            profile_path?: string | null;
        };
        /**
         * TMDBEpisode
         * @description TMDB episode model.
         */
        TMDBEpisode: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Overview */
            overview: string;
            /** Vote Average */
            vote_average: number;
            /** Vote Count */
            vote_count: number;
            /** Air Date */
            air_date?: string | null;
            /** Episode Number */
            episode_number: number;
            /** Episode Type */
            episode_type: string;
            /** Production Code */
            production_code: string;
            /** Runtime */
            runtime?: number | null;
            /** Season Number */
            season_number: number;
            /** Show Id */
            show_id: number;
            /** Still Path */
            still_path?: string | null;
        };
        /**
         * TMDBEpisodeDetail
         * @description Full episode detail.
         *
         *     API: GET /tv/{series_id}/season/{season_number}/episode/{episode_number}
         *     Docs: https://developer.themoviedb.org/reference/tv-episode-details
         */
        TMDBEpisodeDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Overview */
            overview: string;
            /** Season Number */
            season_number: number;
            /** Episode Number */
            episode_number: number;
            /** Episode Type */
            episode_type?: string | null;
            /** Production Code */
            production_code?: string | null;
            /** Air Date */
            air_date?: string | null;
            /** Still Path */
            still_path?: string | null;
            /** Runtime */
            runtime?: number | null;
            /**
             * Vote Average
             * @default 0
             */
            vote_average: number;
            /**
             * Vote Count
             * @default 0
             */
            vote_count: number;
            /** Crew */
            crew?: components["schemas"]["TMDBCrew"][];
            /** Guest Stars */
            guest_stars?: components["schemas"]["TMDBGuestStar"][];
            videos?: components["schemas"]["TMDBVideoResult"] | null;
            images?: components["schemas"]["TMDBEpisodeImages"] | null;
        };
        /**
         * TMDBEpisodeImages
         * @description TMDB episode images collection.
         */
        TMDBEpisodeImages: {
            /** Backdrops */
            backdrops?: components["schemas"]["TMDBImage"][];
            /** Logos */
            logos?: components["schemas"]["TMDBImage"][];
            /** Posters */
            posters?: components["schemas"]["TMDBImage"][];
            /** Stills */
            stills?: components["schemas"]["TMDBImage"][];
        };
        /**
         * TMDBExternalIds
         * @description TMDB external IDs.
         */
        TMDBExternalIds: {
            /** Imdb Id */
            imdb_id?: string | null;
            /** Freebase Mid */
            freebase_mid?: string | null;
            /** Freebase Id */
            freebase_id?: string | null;
            /** Tvdb Id */
            tvdb_id?: number | null;
            /** Tvrage Id */
            tvrage_id?: number | null;
            /** Wikidata Id */
            wikidata_id?: string | null;
            /** Facebook Id */
            facebook_id?: string | null;
            /** Instagram Id */
            instagram_id?: string | null;
            /** Twitter Id */
            twitter_id?: string | null;
        };
        /**
         * TMDBGenre
         * @description TMDB genre model.
         */
        TMDBGenre: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * TMDBGuestStar
         * @description TMDB guest star model.
         */
        TMDBGuestStar: {
            /** Id */
            id: number;
            /** Credit Id */
            credit_id: string;
            /** Name */
            name: string;
            /** Character */
            character: string;
            /** Order */
            order: number;
            /** Profile Path */
            profile_path?: string | null;
        };
        /**
         * TMDBImage
         * @description TMDB image model.
         */
        TMDBImage: {
            /** Aspect Ratio */
            aspect_ratio: number;
            /** Height */
            height: number;
            /** Iso 639 1 */
            iso_639_1?: string | null;
            /** File Path */
            file_path: string;
            /** Vote Average */
            vote_average: number;
            /** Vote Count */
            vote_count: number;
            /** Width */
            width: number;
        };
        /**
         * TMDBImages
         * @description TMDB images collection.
         */
        TMDBImages: {
            /** Backdrops */
            backdrops?: components["schemas"]["TMDBImage"][];
            /** Logos */
            logos?: components["schemas"]["TMDBImage"][];
            /** Posters */
            posters?: components["schemas"]["TMDBImage"][];
        };
        /**
         * TMDBMovieDetail
         * @description TMDB movie detail model.
         */
        TMDBMovieDetail: {
            /** Adult */
            adult: boolean;
            /** Backdrop Path */
            backdrop_path?: string | null;
            /** Belongs To Collection */
            belongs_to_collection?: {
                [key: string]: unknown;
            } | null;
            /** Budget */
            budget: number;
            /** Genres */
            genres?: components["schemas"]["TMDBGenre"][];
            /** Homepage */
            homepage?: string | null;
            /** Id */
            id: number;
            /** Imdb Id */
            imdb_id?: string | null;
            /** Original Language */
            original_language: string;
            /** Original Title */
            original_title: string;
            /** Overview */
            overview?: string | null;
            /** Popularity */
            popularity: number;
            /** Poster Path */
            poster_path?: string | null;
            /** Production Companies */
            production_companies?: components["schemas"]["TMDBProductionCompany"][];
            /** Production Countries */
            production_countries?: components["schemas"]["TMDBProductionCountry"][];
            /** Release Date */
            release_date?: string | null;
            /** Revenue */
            revenue: number;
            /** Runtime */
            runtime?: number | null;
            /** Spoken Languages */
            spoken_languages?: components["schemas"]["TMDBSpokenLanguage"][];
            /** Status */
            status: string;
            /** Tagline */
            tagline?: string | null;
            /** Title */
            title: string;
            /** Video */
            video: boolean;
            /** Vote Average */
            vote_average: number;
            /** Vote Count */
            vote_count: number;
            videos?: components["schemas"]["TMDBVideoResult"] | null;
            images?: components["schemas"]["TMDBImages"] | null;
            external_ids?: components["schemas"]["TMDBExternalIds"] | null;
        };
        /**
         * TMDBNetwork
         * @description TMDB network model.
         */
        TMDBNetwork: {
            /** Id */
            id: number;
            /** Logo Path */
            logo_path?: string | null;
            /** Name */
            name: string;
            /** Origin Country */
            origin_country: string;
        };
        /**
         * TMDBProductionCompany
         * @description TMDB production company model.
         */
        TMDBProductionCompany: {
            /** Id */
            id: number;
            /** Logo Path */
            logo_path?: string | null;
            /** Name */
            name: string;
            /** Origin Country */
            origin_country: string;
        };
        /**
         * TMDBProductionCountry
         * @description TMDB production country model.
         */
        TMDBProductionCountry: {
            /** Iso 3166 1 */
            iso_3166_1: string;
            /** Name */
            name: string;
        };
        /**
         * TMDBSeason
         * @description TMDB season model.
         */
        TMDBSeason: {
            /** Air Date */
            air_date?: string | null;
            /** Episode Count */
            episode_count: number;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Overview */
            overview: string;
            /** Poster Path */
            poster_path?: string | null;
            /** Season Number */
            season_number: number;
            /** Vote Average */
            vote_average: number;
        };
        /**
         * TMDBSeasonDetail
         * @description Full season detail with all episodes.
         *
         *     API: GET /tv/{series_id}/season/{season_number}
         *     Docs: https://developer.themoviedb.org/reference/tv-season-details
         */
        TMDBSeasonDetail: {
            /** Id */
            _id?: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Overview */
            overview: string;
            /** Season Number */
            season_number: number;
            /** Air Date */
            air_date?: string | null;
            /** Poster Path */
            poster_path?: string | null;
            /**
             * Vote Average
             * @default 0
             */
            vote_average: number;
            /** Episodes */
            episodes?: components["schemas"]["TMDBEpisode"][];
            videos?: components["schemas"]["TMDBVideoResult"] | null;
            images?: components["schemas"]["TMDBSeasonImages"] | null;
        };
        /**
         * TMDBSeasonImages
         * @description TMDB season images collection.
         */
        TMDBSeasonImages: {
            /** Backdrops */
            backdrops?: components["schemas"]["TMDBImage"][];
            /** Logos */
            logos?: components["schemas"]["TMDBImage"][];
            /** Posters */
            posters?: components["schemas"]["TMDBImage"][];
        };
        /**
         * TMDBSpokenLanguage
         * @description TMDB spoken language model.
         */
        TMDBSpokenLanguage: {
            /** English Name */
            english_name: string;
            /** Iso 639 1 */
            iso_639_1: string;
            /** Name */
            name: string;
        };
        /**
         * TMDBTVDetail
         * @description TMDB TV show detail model.
         */
        TMDBTVDetail: {
            /** Adult */
            adult: boolean;
            /** Backdrop Path */
            backdrop_path?: string | null;
            /** Created By */
            created_by?: components["schemas"]["TMDBCreatedBy"][];
            /** Episode Run Time */
            episode_run_time?: number[];
            /** First Air Date */
            first_air_date?: string | null;
            /** Genres */
            genres?: components["schemas"]["TMDBGenre"][];
            /** Homepage */
            homepage: string;
            /** Id */
            id: number;
            /** In Production */
            in_production: boolean;
            /** Languages */
            languages?: string[];
            /** Last Air Date */
            last_air_date?: string | null;
            last_episode_to_air?: components["schemas"]["TMDBEpisode"] | null;
            /** Name */
            name: string;
            /** Networks */
            networks?: components["schemas"]["TMDBNetwork"][];
            next_episode_to_air?: components["schemas"]["TMDBEpisode"] | null;
            /** Number Of Episodes */
            number_of_episodes: number;
            /** Number Of Seasons */
            number_of_seasons: number;
            /** Origin Country */
            origin_country?: string[];
            /** Original Language */
            original_language: string;
            /** Original Name */
            original_name: string;
            /** Overview */
            overview: string;
            /** Popularity */
            popularity: number;
            /** Poster Path */
            poster_path?: string | null;
            /** Production Companies */
            production_companies?: components["schemas"]["TMDBProductionCompany"][];
            /** Production Countries */
            production_countries?: components["schemas"]["TMDBProductionCountry"][];
            /** Seasons */
            seasons?: components["schemas"]["TMDBSeason"][];
            /** Spoken Languages */
            spoken_languages?: components["schemas"]["TMDBSpokenLanguage"][];
            /** Status */
            status: string;
            /** Tagline */
            tagline: string;
            /** Type */
            type: string;
            /** Vote Average */
            vote_average: number;
            /** Vote Count */
            vote_count: number;
            videos?: components["schemas"]["TMDBVideoResult"] | null;
            images?: components["schemas"]["TMDBImages"] | null;
            external_ids?: components["schemas"]["TMDBExternalIds"] | null;
        };
        /**
         * TMDBVideo
         * @description TMDB video model.
         */
        TMDBVideo: {
            /** Iso 639 1 */
            iso_639_1: string;
            /** Iso 3166 1 */
            iso_3166_1: string;
            /** Name */
            name: string;
            /** Key */
            key: string;
            /** Site */
            site: string | components["schemas"]["TMDBVideoSite"];
            /** Size */
            size: number;
            /** Type */
            type?: components["schemas"]["TMDBVideoType"] | string | null;
            /** Official */
            official: boolean;
            /** Published At */
            published_at: string;
            /** Id */
            id: string;
        };
        /**
         * TMDBVideoResult
         * @description TMDB video result model.
         */
        TMDBVideoResult: {
            /** Results */
            results?: components["schemas"]["TMDBVideo"][];
        };
        /**
         * TMDBVideoSite
         * @description TMDB video site enumeration.
         * @enum {string}
         */
        TMDBVideoSite: "YouTube";
        /**
         * TMDBVideoType
         * @description TMDB video type enumeration.
         * @enum {string}
         */
        TMDBVideoType: "Trailer" | "Clip" | "Teaser" | "Opening Credits" | "Ending Credits";
        /**
         * TrailerResponse
         * @description Response for trailer extraction.
         */
        TrailerResponse: {
            /** Success */
            success: boolean;
            /** Original Url */
            original_url: string;
            /** Streamable Url */
            streamable_url?: string | null;
            /** M3U8 Url */
            m3u8_url?: string | null;
            /** Quality */
            quality?: string | null;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VideoListResponse
         * @description Response for video sources.
         */
        VideoListResponse: {
            /** @description Type of content (anime, series_movie, adult) */
            content_type: components["schemas"]["ContentType"];
            /**
             * Videos
             * @description Available video sources
             */
            videos: components["schemas"]["VideoSource"][];
        };
        /**
         * VideoSource
         * @description Video source information.
         */
        VideoSource: {
            /** Url */
            url: string;
            /** Original Url */
            original_url: string;
            /** Quality */
            quality: string;
            /** Language */
            language?: string | null;
            /** Format */
            format?: string | null;
            /**
             * Type
             * @description Dub or Sub or original
             * @default original
             */
            type: string | null;
            /** Host */
            host?: string | null;
            /**
             * Requires Proxy
             * @default false
             */
            requires_proxy: boolean;
            /** Headers */
            headers?: {
                [key: string]: string;
            } | null;
            /** Subtitles */
            subtitles?: {
                [key: string]: string;
            }[] | null;
            /** Audios */
            audios?: {
                [key: string]: string;
            }[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved API information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "message": "Anime Backend Service",
                     *       "version": "1.0.0",
                     *       "available_sources": [
                     *         "aniworld",
                     *         "serienstream"
                     *       ],
                     *       "api_docs": "/docs",
                     *       "openapi_schema": "/openapi.json"
                     *     } */
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_sources_sources__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_source_preferences_sources__source__preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_popular_sources__source__popular_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path: {
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSearchResultResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_latest_updates_sources__source__latest_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path: {
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSearchResultResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_content_sources__source__search_get: {
        parameters: {
            query: {
                q: string;
                page?: number;
                lang?: string;
            };
            header?: never;
            path: {
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSearchResultResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_video_sources_sources__source__videos_get: {
        parameters: {
            query: {
                url: string;
                lang?: string;
            };
            header?: never;
            path: {
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoListResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    extract_trailer_url_sources_trailer_get: {
        parameters: {
            query: {
                youtube_url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrailerResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_series_overview_sources__source__series_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path: {
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetailResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_series_seasons_sources__source__series_seasons_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path: {
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonsResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_series_season_sources__source__series_seasons__season_num__get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path: {
                source: string;
                season_num: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_series_episode_sources__source__series_seasons__season_num__episodes__episode_num__get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path: {
                source: string;
                season_num: number;
                episode_num: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_series_movies_sources__source__series_movies_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path: {
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoviesResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_series_movie_sources__source__series_movies__movie_num__get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path: {
                source: string;
                movie_num: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_sources_status_admin_sources_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_cache_stats_admin_cache_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    clear_cache_prefix_admin_cache_clear__prefix__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prefix: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_cache_endpoint_admin_cache_clear_endpoint__endpoint_path__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpoint_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flush_cache_admin_cache_flush_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
